package de.raphaelgoetz.buildLite.registry

import org.bukkit.Material

enum class Door(val material: Material) {
    OAK(Material.OAK_DOOR),
    DARK_OAK(Material.DARK_OAK_DOOR),
    PALE_OAK(Material.PALE_OAK_DOOR),
    SPRUCE(Material.SPRUCE_DOOR),
    BIRCH(Material.BIRCH_DOOR),
    JUNGLE(Material.JUNGLE_DOOR),
    ACACIA(Material.ACACIA_DOOR),
    MANGROVE(Material.MANGROVE_DOOR),
    BAMBOO(Material.BAMBOO_DOOR),
    CRIMSON(Material.CRIMSON_DOOR),
    WARPED(Material.WARPED_DOOR),
    COPPER(Material.COPPER_DOOR),
    CHERRY(Material.CHERRY_DOOR),
    IRON(Material.IRON_DOOR),
    WAXED_COPPER(Material.WAXED_COPPER_DOOR),
    OXIDIZED_COPPER(Material.OXIDIZED_COPPER_DOOR),
    WAXED_OXIDIZED_COPPER(Material.WAXED_OXIDIZED_COPPER_DOOR),
    WEATHERED_COPPER(Material.WEATHERED_COPPER_DOOR),
    WAXED_WEATHERED_COPPER(Material.WAXED_WEATHERED_COPPER_DOOR),
    EXPOSED_COPPER(Material.EXPOSED_COPPER_DOOR),
    WAXED_EXPOSED_COPPER(Material.WAXED_EXPOSED_COPPER_DOOR)
}